# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   pull_request:
      types: [opened, reopened]
      branches: 
        - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
      runs-on: ubuntu-latest
      outputs:
        output1: ${{steps.step1.putputs.test}}
  steps 
